# -*- coding: utf-8 -*-
"""01_exploratory_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oh8EFhLg7UtLsUWjLxrq7PJeAL3sGcT7
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("data/caderno_escutas.csv")

df.head()

# Histograma de BPM

sns.histplot(df['BPM'], kde=True)
plt.title("Distribuição de BPM nas escutas")
plt.xlabel("BPM")
plt.ylabel("Frequência")
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

# Contagem por tonalidade

plt.figure(figsize=(8,5))
sns.countplot(x='Tonalidade', data=df, order=df['Tonalidade'].value_counts().index)
plt.title("Tonalidades mais frequentes")
plt.xlabel("Tonalidade")
plt.ylabel("Número de músicas")
plt.show()

# Dicionário relacionando os modos/escalas com as emoções que representam

modo_para_emocao = {
    'maior': 'Beleza, resolução',
    'menor': 'Melancolia, introspecção',
    'menor/mixolídio': 'Melancolia esperançosa',
    'maior/mixolídio': 'Nostalgia otimista',
    'jônio': 'Alegre',
    'dórico': 'Profundo',
    'frígio': 'Exótico',
    'lídio': 'Etéreo',
    'mixolídio': 'Bluesy',
    'eólio': 'Triste',
    'lócrio': 'Instável'
}

# Relacionando a coluna 'Modo' com uma coluna nova chamada 'Emoção'

df['Modo'] = df['Modo'].str.lower()
df['Emoção'] = df['Modo'].map(modo_para_emocao)

# Emoções mais comuns

plt.figure(figsize=(10,6))
sns.countplot(y='Emoção', data=df, order=df['Emoção'].value_counts().index, palette='coolwarm')
plt.title("Emoções percebidas nas músicas analisadas", fontsize=14)
plt.xlabel("Número de músicas")
plt.ylabel("Emoção (modo/escala)")
plt.tight_layout()
plt.show()